### ISSUE TITLE
Non-Ascii Character in README.md

### ISSUE THREAD

**Issue by macdomat** [coderanger/chef-sentry-handler#4]
Hi, 

As part of our CI/CD tooling we check for non-ascii characters in our cookbooks etc.  

The Readme file for this code has a "proper" '-' instead of the ASCII one.

I've changed this and it appears to work, pull request on it's way in if that's ok?

Thanks,

Matt

**Comment by coderanger** [comment]
I don't see why non-ascii if a problem, please explain.

**Comment by macdomat** [comment]
Chef won't accept non-ascii characters being uploaded to the chef server - I can't tell if the README is uploaded or not from the documentation so we check all files in the cookbook (recipes/templates/etc/etc) for non-ascii characters before we upload.

If the README is ignored by the chef server, then we're ok here and I'll adjust my tooling appropriately otherwise (although I recognise that grammatically I am wrong and you are correct!) I'd love to see this change merged :)

**Comment by coderanger** [comment]
That shouldn't be true, the only places that should block UTF-8 are identifiers like role and node names. If there are issues with Unicode in a file like the readme (or any other content) it is a bug in Chef :)

**Comment by macdomat** [comment]
Fair enough, I'll change my script! :D
